import { v4 as uuidv4 } from 'uuid';
import { addDays, subDays, isBefore, isAfter, differenceInDays } from 'date-fns';
import { STATE_TO_REGION } from './constants';

export const REGIONS = ['North', 'South', 'East', 'West', 'Central'];
export const STATUSES = ['Active', 'Expiring Soon', 'Expired'];

export const calculateStatus = (endDate) => {
  const end = new Date(endDate);
  const now = new Date();
  const diffDays = differenceInDays(end, now);
  
  if (diffDays < 0) return 'Expired';
  if (diffDays <= 30) return 'Expiring Soon';
  return 'Active';
};

// SEED_PROJECTS is generated below

export const SEED_USERS = [
  {
    id: uuidv4(),
    name: 'System Admin',
    email: 'admin@cleanmax.energy',
    password: 'admin',
    phone: '1234567890',
    role: 'admin',
    department: 'IT Operations',
    jobTitle: 'System Administrator',
    twoFactorEnabled: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Viewer User',
    email: 'viewer@cleanmax.energy',
    password: 'viewer',
    phone: '0987654321',
    role: 'viewer',
    department: 'Analytics',
    jobTitle: 'Data Analyst',
    twoFactorEnabled: false,
    createdAt: new Date().toISOString(),
  }
];

const parseDate = (dateStr) => {
  const [day, month, year] = dateStr.split('/');
  return new Date(`${year}-${month}-${day}`).toISOString();
};

const RAW_SEED_VENDORS = [
  {
    id: uuidv4(),
    vendorCode: '101325',
    vendorName: 'SVD Energy',
    vendorType: 'O&M Vendor',
    plantName: 'CHESIRE',
    region: 'South',
    city: 'Hyderabad',
    plantCapacity: 125,
    capacityUnit: 'kWp',
    rate: 30,
    poNumber: '4800000082',
    prNumber: '1700000171',
    contractStart: parseDate('08/02/2024'),
    contractEnd: parseDate('07/02/2025'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101752',
    vendorName: 'Mekanan Energy & Infra Pvt Ltd',
    vendorType: 'O&M Vendor',
    plantName: 'Nykka (B/F/3) - Facel',
    region: 'South',
    city: '',
    plantCapacity: 59.56,
    capacityUnit: 'kWp',
    rate: 211,
    poNumber: '4800000689',
    prNumber: '1200000599',
    contractStart: parseDate('08/12/2025'),
    contractEnd: parseDate('07/12/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101752',
    vendorName: 'Mekanan Energy & Infra Pvt Ltd',
    vendorType: 'O&M Vendor',
    plantName: 'Nykka (B/F/3) - Fashion',
    region: 'South',
    city: '',
    plantCapacity: 29.56,
    capacityUnit: 'kWp',
    rate: 211,
    poNumber: '4800000690',
    prNumber: '1200000600',
    contractStart: parseDate('08/12/2025'),
    contractEnd: parseDate('07/12/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101126',
    vendorName: 'TVS Electronics Limited',
    vendorType: 'O&M Vendor',
    plantName: 'Sanmina Ph1',
    region: 'South',
    city: '',
    plantCapacity: 1041.2,
    capacityUnit: 'kWp',
    rate: 20,
    poNumber: '4800000996',
    prNumber: '1200000635',
    contractStart: parseDate('12/12/2025'),
    contractEnd: parseDate('11/12/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101216',
    vendorName: 'Geana Solar Private Limited',
    vendorType: 'O&M Vendor',
    plantName: 'INT/Innovata IT Services',
    region: 'North',
    city: '',
    plantCapacity: 100.08,
    capacityUnit: 'kWp',
    rate: 25,
    poNumber: '4800000115',
    prNumber: '1200000611',
    contractStart: parseDate('15/12/2025'),
    contractEnd: parseDate('14/12/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101327',
    vendorName: 'Pry Solar Services Private Limited',
    vendorType: 'O&M Vendor',
    plantName: 'Asalpur Mandi',
    region: 'North',
    city: '',
    plantCapacity: 1000,
    capacityUnit: 'kWp',
    rate: 40,
    poNumber: '4800000212',
    prNumber: '1200000617',
    contractStart: parseDate('10/12/2025'),
    contractEnd: parseDate('11/12/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101327',
    vendorName: 'Pry Solar Services Private Limited',
    vendorType: 'O&M Vendor',
    plantName: 'JBM Manesar Site',
    region: 'North',
    city: '',
    plantCapacity: 700,
    capacityUnit: 'kWp',
    rate: 45,
    poNumber: '4800000212',
    prNumber: '1200000617',
    contractStart: parseDate('10/12/2025'),
    contractEnd: parseDate('11/12/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '100035',
    vendorName: 'Winsun Green Pvt Ltd',
    vendorType: 'O&M Vendor',
    plantName: 'MHEI, Chakan',
    region: 'West',
    city: '',
    plantCapacity: 275,
    capacityUnit: 'kWp',
    rate: 40,
    poNumber: '4800000224',
    prNumber: '1200000521',
    contractStart: parseDate('04/02/2025'),
    contractEnd: parseDate('03/02/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '100035',
    vendorName: 'Winsun Green Pvt Ltd',
    vendorType: 'O&M Vendor',
    plantName: 'Godrej Vikhroli',
    region: 'West',
    city: '',
    plantCapacity: 300,
    capacityUnit: 'kWp',
    rate: 20,
    poNumber: '4800000225',
    prNumber: '1200000621',
    contractStart: parseDate('04/02/2025'),
    contractEnd: parseDate('03/02/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101027',
    vendorName: 'Sundraia Solutions Pvt. Ltd.',
    vendorType: 'O&M Vendor',
    plantName: 'KSB Pumps Pimpri',
    region: 'West',
    city: '',
    plantCapacity: 743.50,
    capacityUnit: 'kWp',
    rate: 20,
    poNumber: '4800000750',
    prNumber: '1200000633',
    contractStart: parseDate('12/03/2025'),
    contractEnd: parseDate('11/03/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101131',
    vendorName: 'Sahyog Sales Corporation',
    vendorType: 'O&M Vendor',
    plantName: 'Paramount Bed',
    region: 'North',
    city: '',
    plantCapacity: 100,
    capacityUnit: 'kWp',
    rate: 25,
    poNumber: '4800000241',
    prNumber: '1200000720',
    contractStart: parseDate('26/11/2024'),
    contractEnd: parseDate('25/11/2026'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101131',
    vendorName: 'Sahyog Sales Corporation',
    vendorType: 'O&M Vendor',
    plantName: '7R meghai',
    region: 'North',
    city: '',
    plantCapacity: 464.53,
    capacityUnit: 'kWp',
    rate: 25,
    poNumber: '4800000158',
    prNumber: '1700000067',
    contractStart: parseDate('06/08/2024'),
    contractEnd: parseDate('05/08/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101131',
    vendorName: 'Sahyog Sales Corporation',
    vendorType: 'O&M Vendor',
    plantName: 'Sandhar uhmrr',
    region: 'North',
    city: '',
    plantCapacity: 716.45,
    capacityUnit: 'kWp',
    rate: 25,
    poNumber: '4800000272',
    prNumber: '1700000270',
    contractStart: parseDate('09/08/2024'),
    contractEnd: parseDate('08/08/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '100374',
    vendorName: 'FEATURE GREEN ENERGY SOLUTIONS',
    vendorType: 'O&M Vendor',
    plantName: 'Asahi India',
    region: 'North',
    city: '',
    plantCapacity: 166.27,
    capacityUnit: 'kWp',
    rate: 27,
    poNumber: '4800000272',
    prNumber: '1700000282',
    contractStart: parseDate('04/10/2024'),
    contractEnd: parseDate('03/10/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: '101031',
    vendorName: 'Advik Energy Solution Private Limit',
    vendorType: 'O&M Vendor',
    plantName: 'Carl Zeiss',
    region: 'West',
    city: '',
    plantCapacity: 115.41,
    capacityUnit: 'kWp',
    rate: 20,
    poNumber: '4800000666',
    prNumber: '1200000721',
    contractStart: parseDate('21/02/2025'),
    contractEnd: parseDate('20/02/2027'),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_VENDORS = RAW_SEED_VENDORS.map(v => ({
  ...v,
  status: calculateStatus(v.contractEnd)
}));

export const SEED_PROJECTS = RAW_SEED_VENDORS.map((v, i) => ({
  id: uuidv4(),
  projectCode: `PRJ-${new Date(v.contractStart).getFullYear()}-${String(i + 1).padStart(2, '0')}`,
  projectName: v.plantName,
  client: v.vendorName,
  type: 'O&M Project',
  capacity: v.plantCapacity,
  unit: v.capacityUnit,
  status: calculateStatus(v.contractEnd) === 'Active' ? 'In Progress' : 'Planning',
  completionDate: v.contractStart,
  budget: v.plantCapacity * 50000,
  createdAt: v.createdAt
}));
