import { v4 as uuidv4 } from 'uuid';
import { addDays, subDays, isBefore, isAfter, differenceInDays } from 'date-fns';

export const REGIONS = ['North', 'South', 'East', 'West', 'Central'];
export const STATUSES = ['Active', 'Expiring Soon', 'Expired'];

export const calculateStatus = (endDate) => {
  const end = new Date(endDate);
  const now = new Date();
  const diffDays = differenceInDays(end, now);
  
  if (diffDays < 0) return 'Expired';
  if (diffDays <= 30) return 'Expiring Soon';
  return 'Active';
};

export const SEED_PROJECTS = [
  {
    id: uuidv4(),
    projectCode: 'PRJ-2026-01',
    projectName: 'Bhadla Phase III Expansion',
    client: 'Rajasthan RECL',
    type: 'Solar',
    capacity: 500,
    unit: 'MWp',
    status: 'In Progress',
    completionDate: '2026-12-15',
    budget: 1500000000,
    createdAt: new Date().toISOString()
  },
  {
    id: uuidv4(),
    projectCode: 'PRJ-2026-02',
    projectName: 'Kutch Wind Park',
    client: 'Gujarat GUVNL',
    type: 'Wind',
    capacity: 250,
    unit: 'MW',
    status: 'Planning',
    completionDate: '2027-04-20',
    budget: 850000000,
    createdAt: new Date().toISOString()
  },
  {
    id: uuidv4(),
    projectCode: 'PRJ-2025-11',
    projectName: 'Pavagada Solar Setup',
    client: 'Karnataka KREDL',
    type: 'Solar',
    capacity: 150,
    unit: 'MWp',
    status: 'Completed',
    completionDate: '2026-01-10',
    budget: 450000000,
    createdAt: new Date().toISOString()
  },
  {
    id: uuidv4(),
    projectCode: 'PRJ-2026-04',
    projectName: 'Rewa Hybrid System',
    client: 'MP RUMSL',
    type: 'Hybrid (Solar+Wind)',
    capacity: 300,
    unit: 'MW',
    status: 'In Progress',
    completionDate: '2026-10-05',
    budget: 1200000000,
    createdAt: new Date().toISOString()
  }
];

export const SEED_USERS = [
  {
    id: uuidv4(),
    name: 'System Admin',
    email: 'admin@cleanmax.energy',
    password: 'admin',
    phone: '1234567890',
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Viewer User',
    email: 'viewer@cleanmax.energy',
    password: 'viewer',
    phone: '0987654321',
    role: 'viewer',
    createdAt: new Date().toISOString(),
  }
];

export const SEED_VENDORS = [
  {
    id: uuidv4(),
    vendorCode: 'VND-1001',
    vendorName: 'Adani Green Energy',
    plantName: 'Kamuthi Solar Power Project',
    plantCapacity: 648,
    capacityUnit: 'MWp',
    rate: 4.25,
    poNumber: 'PO-2023-001A',
    prNumber: 'PR-2023-001A',
    region: 'South',
    state: 'Tamil Nadu',
    lat: 9.35,
    lng: 78.39,
    contractStart: subDays(new Date(), 365).toISOString(),
    contractEnd: addDays(new Date(), 700).toISOString(),
    createdAt: subDays(new Date(), 365).toISOString(),
    updatedAt: subDays(new Date(), 365).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1002',
    vendorName: 'Tata Power Solar',
    plantName: 'Pavagada Solar Park',
    plantCapacity: 2050,
    capacityUnit: 'MWp',
    rate: 3.80,
    poNumber: 'PO-2024-054',
    prNumber: 'PR-2024-054',
    region: 'South',
    state: 'Karnataka',
    lat: 14.28,
    lng: 77.42,
    contractStart: subDays(new Date(), 100).toISOString(),
    contractEnd: addDays(new Date(), 15).toISOString(), // Expiring soon
    createdAt: subDays(new Date(), 100).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1003',
    vendorName: 'ReNew Power',
    plantName: 'Bhadla Solar Park',
    plantCapacity: 2245,
    capacityUnit: 'MWp',
    rate: 3.55,
    poNumber: 'PO-2022-101',
    prNumber: 'PR-2022-101',
    region: 'North',
    state: 'Rajasthan',
    lat: 27.53,
    lng: 71.91,
    contractStart: subDays(new Date(), 800).toISOString(),
    contractEnd: subDays(new Date(), 10).toISOString(), // Expired
    createdAt: subDays(new Date(), 800).toISOString(),
    updatedAt: subDays(new Date(), 800).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1004',
    vendorName: 'Azure Power',
    plantName: 'Gujarat Solar Park',
    plantCapacity: 600,
    capacityUnit: 'MWp',
    rate: 4.10,
    poNumber: 'PO-2025-012',
    prNumber: 'PR-2025-012',
    region: 'West',
    state: 'Gujarat',
    lat: 23.90,
    lng: 71.20,
    contractStart: subDays(new Date(), 50).toISOString(),
    contractEnd: addDays(new Date(), 1000).toISOString(),
    createdAt: subDays(new Date(), 50).toISOString(),
    updatedAt: subDays(new Date(), 50).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1005',
    vendorName: 'Hero Future Energies',
    plantName: 'Rewa Ultra Mega Solar',
    plantCapacity: 750,
    capacityUnit: 'MWp',
    rate: 4.50,
    poNumber: 'PO-2023-088',
    prNumber: 'PR-2023-088',
    region: 'Central',
    state: 'Madhya Pradesh',
    lat: 24.48,
    lng: 81.56,
    contractStart: subDays(new Date(), 400).toISOString(),
    contractEnd: addDays(new Date(), 20).toISOString(), // Expiring Soon
    createdAt: subDays(new Date(), 400).toISOString(),
    updatedAt: subDays(new Date(), 400).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1006',
    vendorName: 'Vikram Solar',
    plantName: 'Kurnool Ultra Mega',
    plantCapacity: 1000,
    capacityUnit: 'MWp',
    rate: 5.15,
    poNumber: 'PO-2023-092',
    prNumber: 'PR-2023-092',
    region: 'South',
    state: 'Andhra Pradesh',
    lat: 15.68,
    lng: 78.07,
    contractStart: subDays(new Date(), 600).toISOString(),
    contractEnd: subDays(new Date(), 50).toISOString(), // Expired
    createdAt: subDays(new Date(), 600).toISOString(),
    updatedAt: subDays(new Date(), 600).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1007',
    vendorName: 'Mahindra Susten',
    plantName: 'Bikaner Solar',
    plantCapacity: 250,
    capacityUnit: 'MWp',
    rate: 6.20,
    poNumber: 'PO-2024-005',
    prNumber: 'PR-2024-005',
    region: 'North',
    state: 'Rajasthan',
    lat: 28.02,
    lng: 73.31,
    contractStart: subDays(new Date(), 150).toISOString(),
    contractEnd: addDays(new Date(), 500).toISOString(),
    createdAt: subDays(new Date(), 150).toISOString(),
    updatedAt: subDays(new Date(), 150).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1008',
    vendorName: 'ACME Solar',
    plantName: 'Odisha Solar Plant',
    plantCapacity: 500,
    capacityUnit: 'KWp',
    rate: 4.80,
    poNumber: 'PO-2025-045',
    prNumber: 'PR-2025-045',
    region: 'East',
    state: 'Odisha',
    lat: 20.95,
    lng: 85.09,
    contractStart: subDays(new Date(), 10).toISOString(),
    contractEnd: addDays(new Date(), 365).toISOString(),
    createdAt: subDays(new Date(), 10).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1009',
    vendorName: 'Sterling & Wilson',
    plantName: 'Assam Green Park',
    plantCapacity: 120,
    capacityUnit: 'KWp',
    rate: 5.50,
    poNumber: 'PO-2023-112',
    prNumber: 'PR-2023-112',
    region: 'East',
    state: 'Assam',
    lat: 26.20,
    lng: 92.93,
    contractStart: subDays(new Date(), 300).toISOString(),
    contractEnd: addDays(new Date(), 600).toISOString(),
    createdAt: subDays(new Date(), 300).toISOString(),
    updatedAt: subDays(new Date(), 300).toISOString(),
  },
].map(v => ({...v, status: calculateStatus(v.contractEnd)}));
