import { v4 as uuidv4 } from 'uuid';
import { addDays, subDays, isBefore, isAfter, differenceInDays } from 'date-fns';
import { STATE_TO_REGION } from './constants';

export const REGIONS = ['North', 'South', 'East', 'West', 'Central'];
export const STATUSES = ['Active', 'Expiring Soon', 'Expired'];

export const calculateStatus = (endDate) => {
  const end = new Date(endDate);
  const now = new Date();
  const diffDays = differenceInDays(end, now);
  
  if (diffDays < 0) return 'Expired';
  if (diffDays <= 30) return 'Expiring Soon';
  return 'Active';
};

export const SEED_PROJECTS = [
  {
    id: uuidv4(),
    projectCode: 'PRJ-2026-01',
    projectName: 'Bhadla Phase III Expansion',
    client: 'Rajasthan RECL',
    type: 'Solar',
    capacity: 500,
    unit: 'MWp',
    status: 'In Progress',
    completionDate: '2026-12-15',
    budget: 1500000000,
    createdAt: new Date().toISOString()
  },
  {
    id: uuidv4(),
    projectCode: 'PRJ-2026-02',
    projectName: 'Kutch Wind Park II',
    client: 'Gujarat GUVNL',
    type: 'Wind',
    capacity: 450,
    unit: 'MW',
    status: 'Planning',
    completionDate: '2027-04-20',
    budget: 850000000,
    createdAt: new Date().toISOString()
  },
  {
    id: uuidv4(),
    projectCode: 'PRJ-2025-11',
    projectName: 'Pavagada Solar Setup',
    client: 'Karnataka KREDL',
    type: 'Solar',
    capacity: 350,
    unit: 'MWp',
    status: 'Completed',
    completionDate: '2026-01-10',
    budget: 450000000,
    createdAt: new Date().toISOString()
  },
  {
    id: uuidv4(),
    projectCode: 'PRJ-2026-04',
    projectName: 'Bhadla Phase IV Extension',
    client: 'Rajasthan RECL',
    type: 'Hybrid (Solar+Wind)',
    capacity: 600,
    unit: 'MW',
    status: 'In Progress',
    completionDate: '2026-10-05',
    budget: 1200000000,
    createdAt: new Date().toISOString()
  }
];

export const SEED_USERS = [
  {
    id: uuidv4(),
    name: 'System Admin',
    email: 'admin@cleanmax.energy',
    password: 'admin',
    phone: '1234567890',
    role: 'admin',
    department: 'IT Operations',
    jobTitle: 'System Administrator',
    twoFactorEnabled: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Viewer User',
    email: 'viewer@cleanmax.energy',
    password: 'viewer',
    phone: '0987654321',
    role: 'viewer',
    department: 'Analytics',
    jobTitle: 'Data Analyst',
    twoFactorEnabled: false,
    createdAt: new Date().toISOString(),
  }
];

const RAW_SEED_VENDORS = [
  // 1. Adani Green Energy (Rajasthan, West)
  {
    id: uuidv4(),
    vendorCode: 'VND-1001A',
    vendorName: 'Adani Green Energy',
    vendorType: 'Developer',
    contactPerson: 'Rahul Sharma',
    contactEmail: 'contact@adani.com',
    contactPhone: '+91 98765 43210',
    gstin: '24AAACA0001A1Z1',
    plantName: 'Bhadla Solar Park Phase 1',
    plantCapacity: 450,
    capacityUnit: 'MWp',
    rate: 32.75,
        previousRate: 30.09,
    poNumber: 'PO-2024-042',
    prNumber: 'PR-2024-042',
    region: 'North',
    state: 'Rajasthan',
    city: 'Bhadla',
    lat: 27.53,
    lng: 71.91,
    contractStart: subDays(new Date(), 100).toISOString(),
    contractEnd: addDays(new Date(), 15).toISOString(),
    createdAt: subDays(new Date(), 100).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1001B',
    vendorName: 'Adani Green Energy',
    vendorType: 'Developer',
    contactPerson: 'Rahul Sharma',
    contactEmail: 'contact@adani.com',
    contactPhone: '+91 98765 43210',
    gstin: '24AAACA0001A1Z1',
    plantName: 'Jaisalmer Hybrid Park',
    plantCapacity: 600,
    capacityUnit: 'MW',
    rate: 31.50,
        previousRate: 29.98,
    poNumber: 'PO-2023-001A',
    prNumber: 'PR-2023-001A',
    region: 'North',
    state: 'Rajasthan',
    city: 'Jaisalmer',
    lat: 26.91,
    lng: 70.92,
    contractStart: subDays(new Date(), 365).toISOString(),
    contractEnd: addDays(new Date(), 700).toISOString(),
    createdAt: subDays(new Date(), 365).toISOString(),
    updatedAt: subDays(new Date(), 365).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1001C',
    vendorName: 'Adani Green Energy',
    vendorType: 'Developer',
    contactPerson: 'Rahul Sharma',
    contactEmail: 'contact@adani.com',
    contactPhone: '+91 98765 43210',
    gstin: '24AAACA0001A1Z1',
    plantName: 'Bikaner Solar Farm',
    plantCapacity: 300,
    capacityUnit: 'MWp',
    rate: 33.10,
        previousRate: 30.40,
    poNumber: 'PO-2023-055',
    prNumber: 'PR-2023-055',
    region: 'North',
    state: 'Rajasthan',
    city: 'Bikaner',
    lat: 28.02,
    lng: 73.31,
    contractStart: subDays(new Date(), 150).toISOString(),
    contractEnd: addDays(new Date(), 500).toISOString(),
    createdAt: subDays(new Date(), 150).toISOString(),
    updatedAt: subDays(new Date(), 100).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1001D',
    vendorName: 'Adani Green Energy',
    vendorType: 'Developer',
    contactPerson: 'Rahul Sharma',
    contactEmail: 'contact@adani.com',
    contactPhone: '+91 98765 43210',
    gstin: '24AAACA0001A1Z1',
    plantName: 'Pokhran Renewable Center',
    plantCapacity: 250,
    capacityUnit: 'MWp',
    rate: 34.00,
        previousRate: 31.48,
    poNumber: 'PO-2024-012',
    prNumber: 'PR-2024-012',
    region: 'North',
    state: 'Rajasthan',
    city: 'Pokhran',
    lat: 26.92,
    lng: 71.91,
    contractStart: subDays(new Date(), 50).toISOString(),
    contractEnd: addDays(new Date(), 800).toISOString(),
    createdAt: subDays(new Date(), 50).toISOString(),
    updatedAt: subDays(new Date(), 50).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1001E',
    vendorName: 'Adani Green Energy',
    vendorType: 'Developer',
    contactPerson: 'Rahul Sharma',
    contactEmail: 'contact@adani.com',
    contactPhone: '+91 98765 43210',
    gstin: '24AAACA0001A1Z1',
    plantName: 'Barmer Solar Unit',
    plantCapacity: 150,
    capacityUnit: 'MWp',
    rate: 32.90,
        previousRate: 31.86,
    poNumber: 'PO-2022-099',
    prNumber: 'PR-2022-099',
    region: 'North',
    state: 'Rajasthan',
    city: 'Barmer',
    lat: 25.75,
    lng: 71.40,
    contractStart: subDays(new Date(), 800).toISOString(),
    contractEnd: subDays(new Date(), 10).toISOString(),
    createdAt: subDays(new Date(), 800).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
  },

  // 2. Tata Power Solar (Karnataka, South)
  {
    id: uuidv4(),
    vendorCode: 'VND-1002A',
    vendorName: 'Tata Power Solar',
    vendorType: 'EPC',
    contactPerson: 'Vikram Singh',
    contactEmail: 'solar@tatapower.com',
    contactPhone: '+91 91234 56789',
    gstin: '27AAACT0002B1Z2',
    plantName: 'Pavagada Solar Park',
    plantCapacity: 1050,
    capacityUnit: 'MWp',
    rate: 38.00,
        previousRate: 36.98,
    poNumber: 'PO-2024-054',
    prNumber: 'PR-2024-054',
    region: 'South',
    state: 'Karnataka',
    city: 'Tumkur',
    lat: 14.28,
    lng: 77.42,
    contractStart: subDays(new Date(), 200).toISOString(),
    contractEnd: subDays(new Date(), 10).toISOString(),
    createdAt: subDays(new Date(), 200).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1002B',
    vendorName: 'Tata Power Solar',
    vendorType: 'EPC',
    contactPerson: 'Vikram Singh',
    contactEmail: 'solar@tatapower.com',
    contactPhone: '+91 91234 56789',
    gstin: '27AAACT0002B1Z2',
    plantName: 'Chitradurga Wind-Solar',
    plantCapacity: 400,
    capacityUnit: 'MW',
    rate: 36.50,
        previousRate: 35.34,
    poNumber: 'PO-2025-012',
    prNumber: 'PR-2025-012',
    region: 'South',
    state: 'Karnataka',
    city: 'Chitradurga',
    lat: 14.22,
    lng: 76.39,
    contractStart: subDays(new Date(), 50).toISOString(),
    contractEnd: addDays(new Date(), 1000).toISOString(),
    createdAt: subDays(new Date(), 50).toISOString(),
    updatedAt: subDays(new Date(), 50).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1002C',
    vendorName: 'Tata Power Solar',
    vendorType: 'EPC',
    contactPerson: 'Vikram Singh',
    contactEmail: 'solar@tatapower.com',
    contactPhone: '+91 91234 56789',
    gstin: '27AAACT0002B1Z2',
    plantName: 'Koppal Renewable Site',
    plantCapacity: 300,
    capacityUnit: 'MWp',
    rate: 37.20,
        previousRate: 36.06,
    poNumber: 'PO-2023-112',
    prNumber: 'PR-2023-112',
    region: 'South',
    state: 'Karnataka',
    city: 'Koppal',
    lat: 15.34,
    lng: 76.15,
    contractStart: subDays(new Date(), 300).toISOString(),
    contractEnd: addDays(new Date(), 600).toISOString(),
    createdAt: subDays(new Date(), 300).toISOString(),
    updatedAt: subDays(new Date(), 200).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1002D',
    vendorName: 'Tata Power Solar',
    vendorType: 'EPC',
    contactPerson: 'Vikram Singh',
    contactEmail: 'solar@tatapower.com',
    contactPhone: '+91 91234 56789',
    gstin: '27AAACT0002B1Z2',
    plantName: 'Gadag Wind Farm',
    plantCapacity: 250,
    capacityUnit: 'MW',
    rate: 35.80,
        previousRate: 34.72,
    poNumber: 'PO-2024-077',
    prNumber: 'PR-2024-077',
    region: 'South',
    state: 'Karnataka',
    city: 'Gadag',
    lat: 15.43,
    lng: 75.63,
    contractStart: subDays(new Date(), 120).toISOString(),
    contractEnd: addDays(new Date(), 120).toISOString(),
    createdAt: subDays(new Date(), 120).toISOString(),
    updatedAt: subDays(new Date(), 50).toISOString(),
  },

  // 3. ReNew Power (Madhya Pradesh, Central)
  {
    id: uuidv4(),
    vendorCode: 'VND-1003A',
    vendorName: 'ReNew Power',
    vendorType: 'IPP',
    contactPerson: 'Amit Kumar',
    contactEmail: 'amit.k@renewpower.in',
    contactPhone: '+91 98888 77777',
    gstin: '06AAACR0003C1Z3',
    plantName: 'Rewa Ultra Mega Solar',
    plantCapacity: 750,
    capacityUnit: 'MWp',
    rate: 39.50,
        previousRate: 37.67,
    poNumber: 'PO-2023-088',
    prNumber: 'PR-2023-088',
    region: 'Central',
    state: 'Madhya Pradesh',
    city: 'Rewa',
    lat: 24.48,
    lng: 81.56,
    contractStart: subDays(new Date(), 400).toISOString(),
    contractEnd: addDays(new Date(), 20).toISOString(),
    createdAt: subDays(new Date(), 400).toISOString(),
    updatedAt: subDays(new Date(), 400).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1003B',
    vendorName: 'ReNew Power',
    vendorType: 'IPP',
    contactPerson: 'Amit Kumar',
    contactEmail: 'amit.k@renewpower.in',
    contactPhone: '+91 98888 77777',
    gstin: '06AAACR0003C1Z3',
    plantName: 'Neemuch Solar Plant',
    plantCapacity: 300,
    capacityUnit: 'MWp',
    rate: 38.20,
        previousRate: 36.59,
    poNumber: 'PO-2024-022',
    prNumber: 'PR-2024-022',
    region: 'Central',
    state: 'Madhya Pradesh',
    city: 'Neemuch',
    lat: 24.46,
    lng: 74.87,
    contractStart: subDays(new Date(), 180).toISOString(),
    contractEnd: addDays(new Date(), 800).toISOString(),
    createdAt: subDays(new Date(), 180).toISOString(),
    updatedAt: subDays(new Date(), 180).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1003C',
    vendorName: 'ReNew Power',
    vendorType: 'IPP',
    contactPerson: 'Amit Kumar',
    contactEmail: 'amit.k@renewpower.in',
    contactPhone: '+91 98888 77777',
    gstin: '06AAACR0003C1Z3',
    plantName: 'Agar Solar Park',
    plantCapacity: 250,
    capacityUnit: 'MWp',
    rate: 39.10,
        previousRate: 36.78,
    poNumber: 'PO-2023-104',
    prNumber: 'PR-2023-104',
    region: 'Central',
    state: 'Madhya Pradesh',
    city: 'Agar',
    lat: 23.71,
    lng: 76.01,
    contractStart: subDays(new Date(), 250).toISOString(),
    contractEnd: addDays(new Date(), 300).toISOString(),
    createdAt: subDays(new Date(), 250).toISOString(),
    updatedAt: subDays(new Date(), 250).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1003D',
    vendorName: 'ReNew Power',
    vendorType: 'IPP',
    contactPerson: 'Amit Kumar',
    contactEmail: 'amit.k@renewpower.in',
    contactPhone: '+91 98888 77777',
    gstin: '06AAACR0003C1Z3',
    plantName: 'Shajapur Solar Unit',
    plantCapacity: 200,
    capacityUnit: 'MWp',
    rate: 38.50,
        previousRate: 36.26,
    poNumber: 'PO-2022-041',
    prNumber: 'PR-2022-041',
    region: 'Central',
    state: 'Madhya Pradesh',
    city: 'Shajapur',
    lat: 23.42,
    lng: 76.27,
    contractStart: subDays(new Date(), 600).toISOString(),
    contractEnd: subDays(new Date(), 5).toISOString(),
    createdAt: subDays(new Date(), 600).toISOString(),
    updatedAt: subDays(new Date(), 600).toISOString(),
  },

  // 4. Vikram Solar (Andhra Pradesh, South)
  {
    id: uuidv4(),
    vendorCode: 'VND-1004A',
    vendorName: 'Vikram Solar',
    vendorType: 'Manufacturer',
    contactPerson: 'Sanjay Gupta',
    contactEmail: 'info@vikramsolar.com',
    contactPhone: '+91 99999 00000',
    gstin: '19AAACV0004D1Z4',
    plantName: 'Kurnool Ultra Mega',
    plantCapacity: 1000,
    capacityUnit: 'MWp',
    rate: 35.00,
        previousRate: 32.60,
    poNumber: 'PO-2023-092',
    prNumber: 'PR-2023-092',
    region: 'South',
    state: 'Andhra Pradesh',
    city: 'Kurnool',
    lat: 15.68,
    lng: 78.07,
    contractStart: subDays(new Date(), 600).toISOString(),
    contractEnd: subDays(new Date(), 50).toISOString(),
    createdAt: subDays(new Date(), 600).toISOString(),
    updatedAt: subDays(new Date(), 600).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1004B',
    vendorName: 'Vikram Solar',
    vendorType: 'Manufacturer',
    contactPerson: 'Sanjay Gupta',
    contactEmail: 'info@vikramsolar.com',
    contactPhone: '+91 99999 00000',
    gstin: '19AAACV0004D1Z4',
    plantName: 'Kadapa Solar Park',
    plantCapacity: 250,
    capacityUnit: 'MWp',
    rate: 36.20,
        previousRate: 34.70,
    poNumber: 'PO-2024-003',
    prNumber: 'PR-2024-003',
    region: 'South',
    state: 'Andhra Pradesh',
    city: 'Kadapa',
    lat: 14.46,
    lng: 78.82,
    contractStart: subDays(new Date(), 100).toISOString(),
    contractEnd: addDays(new Date(), 500).toISOString(),
    createdAt: subDays(new Date(), 100).toISOString(),
    updatedAt: subDays(new Date(), 100).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1004C',
    vendorName: 'Vikram Solar',
    vendorType: 'Manufacturer',
    contactPerson: 'Sanjay Gupta',
    contactEmail: 'info@vikramsolar.com',
    contactPhone: '+91 99999 00000',
    gstin: '19AAACV0004D1Z4',
    plantName: 'Ananthapuramu Solar',
    plantCapacity: 400,
    capacityUnit: 'MWp',
    rate: 35.80,
        previousRate: 33.11,
    poNumber: 'PO-2023-156',
    prNumber: 'PR-2023-156',
    region: 'South',
    state: 'Andhra Pradesh',
    city: 'Anantapur',
    lat: 14.68,
    lng: 77.60,
    contractStart: subDays(new Date(), 300).toISOString(),
    contractEnd: addDays(new Date(), 30).toISOString(),
    createdAt: subDays(new Date(), 300).toISOString(),
    updatedAt: subDays(new Date(), 300).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1004D',
    vendorName: 'Vikram Solar',
    vendorType: 'Manufacturer',
    contactPerson: 'Sanjay Gupta',
    contactEmail: 'info@vikramsolar.com',
    contactPhone: '+91 99999 00000',
    gstin: '19AAACV0004D1Z4',
    plantName: 'Chittoor Hybrid Project',
    plantCapacity: 300,
    capacityUnit: 'MW',
    rate: 37.10,
        previousRate: 34.96,
    poNumber: 'PO-2025-021',
    prNumber: 'PR-2025-021',
    region: 'South',
    state: 'Andhra Pradesh',
    city: 'Chittoor',
    lat: 13.21,
    lng: 79.10,
    contractStart: subDays(new Date(), 50).toISOString(),
    contractEnd: addDays(new Date(), 900).toISOString(),
    createdAt: subDays(new Date(), 50).toISOString(),
    updatedAt: subDays(new Date(), 50).toISOString(),
  },
  
  // 5. Hero Future Energies (West Bengal, East)
  {
    id: uuidv4(),
    vendorCode: 'VND-1005A',
    vendorName: 'Hero Future Energies',
    vendorType: 'Developer',
    contactPerson: 'Arun Chatterjee',
    contactEmail: 'arun.c@herofuture.com',
    contactPhone: '+91 91111 22222',
    gstin: '19AAACH0005E1Z5',
    plantName: 'Purulia Solar Farm',
    plantCapacity: 200,
    capacityUnit: 'MWp',
    rate: 34.50,
    previousRate: 32.10,
    poNumber: 'PO-2024-089',
    prNumber: 'PR-2024-089',
    region: 'East',
    state: 'West Bengal',
    city: 'Purulia',
    lat: 23.33,
    lng: 86.36,
    contractStart: subDays(new Date(), 180).toISOString(),
    contractEnd: addDays(new Date(), 1200).toISOString(),
    createdAt: subDays(new Date(), 180).toISOString(),
    updatedAt: subDays(new Date(), 90).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1005B',
    vendorName: 'Hero Future Energies',
    vendorType: 'Developer',
    contactPerson: 'Arun Chatterjee',
    contactEmail: 'arun.c@herofuture.com',
    contactPhone: '+91 91111 22222',
    gstin: '19AAACH0005E1Z5',
    plantName: 'Bhubaneswar Wind Park',
    plantCapacity: 150,
    capacityUnit: 'MW',
    rate: 36.20,
    previousRate: 34.10,
    poNumber: 'PO-2023-112',
    prNumber: 'PR-2023-112',
    region: 'East',
    state: 'Odisha',
    city: 'Bhubaneswar',
    lat: 20.29,
    lng: 85.82,
    contractStart: subDays(new Date(), 250).toISOString(),
    contractEnd: addDays(new Date(), 400).toISOString(),
    createdAt: subDays(new Date(), 250).toISOString(),
    updatedAt: subDays(new Date(), 120).toISOString(),
  },
  
  // 6. Azure Power (Punjab, North)
  {
    id: uuidv4(),
    vendorCode: 'VND-1006A',
    vendorName: 'Azure Power',
    vendorType: 'IPP',
    contactPerson: 'Gurpreet Singh',
    contactEmail: 'gurpreet@azurepower.com',
    contactPhone: '+91 88888 33333',
    gstin: '03AAACA0006F1Z6',
    plantName: 'Bhatinda Solar Hub',
    plantCapacity: 250,
    capacityUnit: 'MWp',
    rate: 33.50,
    previousRate: 31.80,
    poNumber: 'PO-2022-045',
    prNumber: 'PR-2022-045',
    region: 'North',
    state: 'Punjab',
    city: 'Bhatinda',
    lat: 30.21,
    lng: 74.94,
    contractStart: subDays(new Date(), 400).toISOString(),
    contractEnd: addDays(new Date(), 600).toISOString(),
    createdAt: subDays(new Date(), 400).toISOString(),
    updatedAt: subDays(new Date(), 200).toISOString(),
  },
  {
    id: uuidv4(),
    vendorCode: 'VND-1006B',
    vendorName: 'Azure Power',
    vendorType: 'IPP',
    contactPerson: 'Gurpreet Singh',
    contactEmail: 'gurpreet@azurepower.com',
    contactPhone: '+91 88888 33333',
    gstin: '03AAACA0006F1Z6',
    plantName: 'Kanpur Solar Rooftop',
    plantCapacity: 100,
    capacityUnit: 'MWp',
    rate: 35.10,
    previousRate: 33.90,
    poNumber: 'PO-2024-002',
    prNumber: 'PR-2024-002',
    region: 'North',
    state: 'Uttar Pradesh',
    city: 'Kanpur',
    lat: 26.44,
    lng: 80.33,
    contractStart: subDays(new Date(), 60).toISOString(),
    contractEnd: addDays(new Date(), 800).toISOString(),
    createdAt: subDays(new Date(), 60).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
  }
].map(v => ({
  ...v, 
  status: calculateStatus(v.contractEnd)
}));

export const SEED_VENDORS = RAW_SEED_VENDORS.map(v => ({
  ...v,
  region: STATE_TO_REGION[v.state] || v.region
}));
